### ISSUE TITLE
recursive context inclusion when processing http://stuchalk.github.io/scidata/contexts/scidata.jsonld

### ISSUE THREAD

**Issue by lewismc** [stuchalk/scidata#3]
Hi @stuchalk , when I attempt to process [scidata.jsonld](http://stuchalk.github.io/scidata/contexts/scidata.jsonld) using the [Apache Any23](http://any23.apache.org) service available at [any23.org](http://any23.org), I experience the following issue
```
org.apache.any23.extractor.ExtractionException: Error while parsing RDF document.
	at org.apache.any23.extractor.rdf.BaseRDFExtractor.run(BaseRDFExtractor.java:109)
	at org.apache.any23.extractor.rdf.BaseRDFExtractor.run(BaseRDFExtractor.java:41)
	at org.apache.any23.extractor.SingleDocumentExtraction.runExtractor(SingleDocumentExtraction.java:464)
	at org.apache.any23.extractor.SingleDocumentExtraction.run(SingleDocumentExtraction.java:255)
	at org.apache.any23.Any23.extract(Any23.java:300)
	at org.apache.any23.Any23.extract(Any23.java:452)
	at org.apache.any23.servlet.WebResponder.runExtraction(WebResponder.java:114)
	at org.apache.any23.servlet.Servlet.doGet(Servlet.java:79)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:618)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:301)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:503)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:136)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:74)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:526)
	at org.apache.coyote.ajp.AbstractAjpProcessor.process(AbstractAjpProcessor.java:794)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:652)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1575)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1533)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.openrdf.rio.RDFParseException: Could not parse JSONLD
	at com.github.jsonldjava.sesame.SesameJSONLDParser.parse(SesameJSONLDParser.java:67)
	at org.apache.any23.extractor.rdf.BaseRDFExtractor.run(BaseRDFExtractor.java:105)
	... 29 more
Caused by: com.github.jsonldjava.core.JsonLdError: recursive context inclusion: http://stuchalk.github.io/scidata/contexts/scidata_parameter.jsonld
	at com.github.jsonldjava.core.Context.parse(Context.java:163)
	at com.github.jsonldjava.core.Context.parse(Context.java:179)
	at com.github.jsonldjava.core.Context.parse(Context.java:179)
	at com.github.jsonldjava.core.Context.parse(Context.java:251)
	at com.github.jsonldjava.core.JsonLdApi.expand(JsonLdApi.java:533)
	at com.github.jsonldjava.core.JsonLdApi.expand(JsonLdApi.java:980)
	at com.github.jsonldjava.core.JsonLdProcessor.expand(JsonLdProcessor.java:137)
	at com.github.jsonldjava.core.JsonLdProcessor.toRDF(JsonLdProcessor.java:472)
	at com.github.jsonldjava.sesame.SesameJSONLDParser.parse(SesameJSONLDParser.java:65)
	... 30 more
```
[Section 3.2.2](https://www.w3.org/TR/json-ld-api/#context-processing-algorithm) of the [JSON-LD 1.0 Processing Algorithms and API](https://www.w3.org/TR/json-ld-api/) defines "...If context is in the remote contexts array, a recursive context inclusion error has been detected and processing is aborted; otherwise, add context to remote contexts.". 

Am I interpreting this incorrectly...? Thanks for any insight.

**Comment by stuchalk** [comment]
So, the file that you tested was not a data file but a context file so looking at the apache site I am not sure it was the right file to try.  I just loaded http://stuchalk.github.io/scidata/examples/ddb/ddb.jsonld into the JSON-LD playground (http://json-ld.org/playground/) and it works fine.  Maybe you can try this file on Apache Any23 site and let me know what happens?
